server:
  port: 8081
spring:
  application:
    name: item-service
#    datasource:
#      url: jdbc:mysql://localhost:3306/leyou?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#      username: pub
#      password: pub
#      hikari:
#        maximum-pool-size: 30
#        minimum-idle: 10
#  datasource:
#    dbcp2:
#      driver:
#      username: pub
#      password: pub

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    hostname: 127.0.0.1
